version: 2.1

jobs:
  build:
    working_directory: ~/client
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    working_directory: ~/client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c0:5e:29:dd:a8:39:34:85:f9:cd:82:cc:97:ef:0f:75"
      - checkout
      - run:
          name: Push Main to Production
          command: |
            git checkout main
            git pull
            git checkout -b production
            git push origin production

workflows:
  version: 2
  test:
    jobs:
      - build
  deploy:
    jobs:
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
