version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "c0:5e:29:dd:a8:39:34:85:f9:cd:82:cc:97:ef:0f:75"
      - checkout
      - run:
          name: Push Main to Production
          command: |
            git push https://github.com/Kody-Eguchi/nourishd main:production

workflows:
  version: 2
  test:
    jobs:
      - build
